### ISSUE TITLE
How to activate bot

### ISSUE THREAD

**Issue by ScienceBear** [tomaarsen/TwitchMarkovChain#13]
This is a very naive question, but I have managed to download and install the bot using conda.

How do I activate it? Do I simply need to link it to a bot account, or is there something else I need to do?

**Comment by DoctorInsano** [comment]
Hey there! Simply activating the bot is relatively simple. You just need to make sure Python 3 is installed and have the code downloaded.

From there, open `settings.txt`
You then need to add the channel to the `Channel` part of the settings. It is in the form of \#StreamerName
Then generate an oauth token [Here](https://twitchapps.com/tmi/) and place the generated token in the `Authentication`
Finally, add your bot name to the `Nickname` setting.

After that, setup is done, and the bot can be run via the console with `python MarkovChainBot.py`

**Comment by ScienceBear** [comment]
Thanks for the very quick response (also useful for other users) and help on Twitch chat earlier! I'll close this once I confirm that the bot is working. Very grateful!
