### ISSUE TITLE
bot breaking up words with single quotation marks in them

### ISSUE THREAD

**Issue by tradingaddict** [tomaarsen/TwitchMarkovChain#29]
Trying to generate sentences with !g and words such as "I'm", "haven't", "can't" etc. doesn't work, I believe they are saved properly in the database and the bot uses them normally when it picks them itself, but it breaks if you try to put them in a !g command. 

Typing "!g i've" makes the bot say "I haven't learned what to do with "i 've" yet."
Typing "!g can't" makes it say "I haven't learned what to do with "ca n't" yet."

It does have data for the actual words in the database but it looks like something goes wrong with splitting the words and putting them back together when generating.

**Comment by tomaarsen** [comment]
This should be fixed now in the latest release. Feel free to upgrade. Your old database won't immediately update, but new entries should be correct now.

**Comment by tomaarsen** [comment]
I've opened up an issue on NLTK for the tokenizing issue I mentioned: https://github.com/nltk/nltk/issues/3069.
