### ISSUE TITLE
bot stuck to the wrong account

### ISSUE THREAD

**Issue by arcaneartist** [tomaarsen/TwitchMarkovChain#30]
apologies if this is the wrong place for this kind of issue, but I seem to have gotten my installation of the bot stuck to the wrong account. I understand how it happened (I used the wrong OAuth password) but I can't figure out how to fix it, as no amount of modifying (or even deleting) files on my computer changes anything. presumably there are files uploaded elsewhere that would need to be modified/deleted to get this set up on the right account, but I don't know how to do that.

**Comment by tomaarsen** [comment]
The only files used are local, and the only file that is in charge of determining the account used is `settings.json`. The `Nickname` and `Authentication` determine which account is used as the bot account, i.e. the account that responds to messages. If you want to enable the bot to run on a different Twitch channel, then you would have to change the value under `Channel`. There's no uploaded files, so there's no need to worry about that.

**Comment by arcaneartist** [comment]
I tried changing the nickname and authentication, but it continued to use the account I accidently set it to in the beginning as if nothing had changed. the only thing that seems to have effected it was disconnecting the Oauth password generator from the account it was linked to, but all that has done is make it to where it gives me a "Login authentication failed" error regardless of what password I put.

**Comment by arcaneartist** [comment]
I'm not sure how I fixed it, but its working now

**Comment by tomaarsen** [comment]
Glad to hear it!
