### ISSUE TITLE
Problem with TwitchWebSocket while trying to run MarkovChainBot.py

### ISSUE THREAD

**Issue by Ursometamorfo** [tomaarsen/TwitchMarkovChain#35]
Hello! I'm a long time user of your program and so far it has been working flawlessly! But recently i formatted my SSD and while trying to set up the bot again i installed Python, Git and ran the requirement.txt command with no problems, but as soon as i tried to run the file MarkovChainBot.py it gave me this error:

```
Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\TwitchMarkovChain-2.4\TwitchMarkovChain-2.4\MarkovChainBot.py", line 4, in <module>
    from TwitchWebsocket import Message, TwitchWebsocket
  File "C:\Users\Administrator\Downloads\TwitchMarkovChain-2.4\TwitchMarkovChain-2.4\TwitchWebsocket.py", line 8, in <module>
    from TwitchWebsocket.Message import Message
ModuleNotFoundError: No module named 'TwitchWebsocket.Message'; 'TwitchWebsocket' is not a package

```
I tried to download the TwitchWebSocket myself and copy the message and twitchwebsocket files into the folder but to no avail, rerunning the requirements command just gave back that the requirement was already satisfied, so i'm not sure what's going on or how to fix, any help is highly appreciated!

**Comment by tomaarsen** [comment]
Hello!

According to your logs, you have a file called `TwitchWebsocket.py`. This is probably from copying the files locally. When it then tries to do
```
from TwitchWebsocket.Message import Message
```
then it'll see `TwitchWebsocket` as the current file, and there's no `Message` defined in the current file. Perhaps you could get around this by copying the TwitchWebsocket *folder*, i.e. [this full folder](https://github.com/tomaarsen/TwitchWebsocket/tree/master/TwitchWebsocket).

However, normally it should work with just `pip install TwitchWebsocket`, but then make sure there's no local file called `TwitchWebsocket.py`, or that one will have priority. I think you probably tried that already based on your message. If you run `pip show TwitchWebsocket`, does it then show a package? 

A relatively common error with that is that the `pip` is from a different `python` than the `python` that you're running the program with. You can get around this by doing `python -m pip show TwitchWebsocket` and `python -m pip install TwitchWebsocket`. Then you know for sure that the `pip` and `python` "match".

Hopefully this helps you in the right direction already, but please let me know if you still can't get it to work, and I'll try to help with some more details.

- Tom Aarsen

**Comment by Ursometamorfo** [comment]
Hi again! THE PROBLEM WAS SOLVED! 
A quick rundown of my troubleshooting would be:

- I did all the tests you suggested and confirmed they were using the same python! 
- Dragging over the files didn't seem to solve the problem either
- Not knowing what to do, i decided to start from scratch, uninstalled all pythons instances i could find and installed ONLY python 11 through Microsoft store and reinstalled Git as well.
- After that, i redownloaded the master for the Bot and ran the requirements command
- Had a weird issue where python would open when asked to run "MarkovChainBot.py" but closed instantly, rebooting the computer fixed that.
- After that the bot seemed to run just fine, the only "anomaly" noticed was the line 

```
[2023-05-11 11:04:07,476] [__main__] [INFO    ] - Fetching mod list...
[2023-05-11 11:04:07,699] [__main__] [INFO    ] - Unrecognized command: /mods
```

Aside from that, it seems it's working as intended!!! Thank you very much for the help and quick answer!

**Comment by tomaarsen** [comment]
I'm glad that you got it working, despite all that you had to go through to get it to work again!

As for the anomaly, I'm aware of it. Twitch removed most (or all?) of the "slash commands" like `/mods`. However, it shouldn't affect you - I think it was only used to allow moderators to update the cooldown and disable/enable the bot on the fly from the chat.

**Comment by tomaarsen** [comment]
I'll close this now :)
